########### M3 CONFIG ######################
hostname: meka-man
factory_rt_libs:
  - /usr/local/lib/libm3toolbox.so
  - /usr/local/lib/libm3hardware.so
  - /usr/local/lib/libm3chains.so
  - /usr/local/lib/libm3robots.so
  - /usr/local/lib/libm3robot_ctrl.so
  - /usr/local/lib/libm3vehicles.so
factory_py_libs:
  - /usr/local/lib/python2.7/dist-packages/m3/m3meka_factory_proxy.py

sys_test: simc

rt_components:
  pwr:
    m3pwr_pwr042: m3pwr
    m3pwr_pwr038: m3pwr
#  sys:
#    m3monitor_m0: m3monitor
  mz7:
    m3actuator_mz7_j0: m3actuator
    m3joint_mz7_j0: m3joint_zlift
    m3joint_shm_mz7_j0: m3joint_zlift_shm
  mb7:
    m3omnibase_shm_mb7: m3omnibase_shm
    m3omnibase_mb7: m3omnibase
    m3joint_array_mb7: m3joint_array
    m3actuator_mb7_j0: m3actuator
    m3joint_mb7_j0: m3joint
    m3actuator_mb7_j1: m3actuator
    m3joint_mb7_j1: m3joint
    m3actuator_mb7_j2: m3actuator
    m3joint_mb7_j2: m3joint
    m3actuator_mb7_j3: m3actuator
    m3joint_mb7_j3: m3joint
    m3actuator_mb7_j4: m3actuator
    m3joint_mb7_j4: m3joint
    m3actuator_mb7_j5: m3actuator
    m3joint_mb7_j5: m3joint
    m3actuator_mb7_j6: m3actuator
    m3joint_mb7_j6: m3joint
    m3actuator_mb7_j7: m3actuator
    m3joint_mb7_j7: m3joint
  mh24:
    m3actuator_mh24_j0: m3actuator
    m3actuator_mh24_j1: m3actuator
    m3actuator_mh24_j2: m3actuator
    m3actuator_mh24_j3: m3actuator
    m3actuator_mh24_j4: m3actuator
    m3joint_mh24_j0: m3joint
    m3joint_mh24_j1: m3joint
    m3joint_mh24_j2: m3joint
    m3joint_mh24_j3: m3joint
    m3joint_mh24_j4: m3joint
    m3hand_mh24: m3hand
  mh26:
    m3actuator_mh26_j0: m3actuator
    m3actuator_mh26_j1: m3actuator
    m3actuator_mh26_j2: m3actuator
    m3actuator_mh26_j3: m3actuator
    m3actuator_mh26_j4: m3actuator
    m3joint_mh26_j0: m3joint
    m3joint_mh26_j1: m3joint
    m3joint_mh26_j2: m3joint
    m3joint_mh26_j3: m3joint
    m3joint_mh26_j4: m3joint
    m3hand_mh26: m3hand
  ms8:
    m3actuator_ms8_j0: m3actuator
    m3actuator_ms8_j1: m3actuator    
    m3ctrl_simple_ms8_j0: m3ctrl_simple
    m3ctrl_simple_ms8_j1: m3ctrl_simple
    m3joint_ms8_j0: m3joint
    m3joint_ms8_j1: m3joint
    m3head_ms8: m3head
    m3dynamatics_s3r1_simc_ms8: m3dynamatics
  mt6:
    m3actuator_mt6_j0: m3actuator
    m3actuator_mt6_j1: m3actuator
    m3ctrl_simple_mt6_j0: m3ctrl_simple
    m3ctrl_simple_mt6_j1: m3ctrl_simple
    m3joint_mt6_j0: m3joint
    m3joint_mt6_j1: m3joint
    m3joint_slave_mt6_j2: m3joint_slave
    m3torso_mt6: m3torso
    m3dynamatics_bimanual_mt6: m3dynamatics
  ma29:
    m3actuator_ma29_j0: m3actuator
    m3actuator_ma29_j1: m3actuator
    m3actuator_ma29_j2: m3actuator
    m3actuator_ma29_j3: m3actuator
    m3actuator_ma29_j4: m3actuator
    m3actuator_ma29_j5: m3actuator
    m3actuator_ma29_j6: m3actuator
    m3ctrl_simple_ma29_j0: m3ctrl_simple
    m3ctrl_simple_ma29_j1: m3ctrl_simple
    m3ctrl_simple_ma29_j2: m3ctrl_simple
    m3ctrl_simple_ma29_j3: m3ctrl_simple
    m3ctrl_simple_ma29_j4: m3ctrl_simple
    m3ctrl_simple_ma29_j5: m3ctrl_simple
    m3ctrl_simple_ma29_j6: m3ctrl_simple
    m3joint_ma29_j0: m3joint
    m3joint_ma29_j1: m3joint
    m3joint_ma29_j2: m3joint
    m3joint_ma29_j3: m3joint
    m3joint_ma29_j4: m3joint
    m3joint_ma29_j5: m3joint
    m3joint_ma29_j6: m3joint
    m3arm_ma29: m3arm
    m3dynamatics_right_h2R5_fts_ma29: m3dynamatics
    m3loadx6_ma29_l0: m3loadx6
  ma30:
    m3actuator_ma30_j0: m3actuator
    m3actuator_ma30_j1: m3actuator
    m3actuator_ma30_j2: m3actuator
    m3actuator_ma30_j3: m3actuator
    m3actuator_ma30_j4: m3actuator
    m3actuator_ma30_j5: m3actuator
    m3actuator_ma30_j6: m3actuator
    m3ctrl_simple_ma30_j0: m3ctrl_simple
    m3ctrl_simple_ma30_j1: m3ctrl_simple
    m3ctrl_simple_ma30_j2: m3ctrl_simple
    m3ctrl_simple_ma30_j3: m3ctrl_simple
    m3ctrl_simple_ma30_j4: m3ctrl_simple
    m3ctrl_simple_ma30_j5: m3ctrl_simple
    m3ctrl_simple_ma30_j6: m3ctrl_simple
    m3joint_ma30_j0: m3joint
    m3joint_ma30_j1: m3joint
    m3joint_ma30_j2: m3joint
    m3joint_ma30_j3: m3joint
    m3joint_ma30_j4: m3joint
    m3joint_ma30_j5: m3joint
    m3joint_ma30_j6: m3joint
    m3arm_ma30: m3arm
    m3dynamatics_left_h2R5_fts_ma30: m3dynamatics
    m3loadx6_ma30_l0: m3loadx6
  mr18:
    m3humanoid_right_left_arm_torso_head_mr18: m3humanoid  
#     m3humanoid_head_mr14: m3humanoid
#     m3humanoid_right_arm_mr18: m3humanoid
#     m3humanoid_right_left_arm_mr18: m3humanoid
#     m3humanoid_right_left_arm_head_mr18: m3humanoid
#    m3haptic_demo_hd0: m3haptic_demo
#     m3humanoid_left_arm_mr18: m3humanoid
#     m3humanoid_right_arm_head_mr18: m3humanoid
    m3humanoid_shm18: m3humanoid_shm
ec_components:
  mh26:
    m3actuator_ec_mh26_j0: m3actuator_ec
    m3actuator_ec_mh26_j1: m3actuator_ec
    m3actuator_ec_mh26_j2: m3actuator_ec
    m3actuator_ec_mh26_j3: m3actuator_ec
    m3actuator_ec_mh26_j4: m3actuator_ec
  mh24:
    m3actuator_ec_mh24_j0: m3actuator_ec
    m3actuator_ec_mh24_j1: m3actuator_ec
    m3actuator_ec_mh24_j2: m3actuator_ec
    m3actuator_ec_mh24_j3: m3actuator_ec
    m3actuator_ec_mh24_j4: m3actuator_ec
  mz7:
    m3actuator_ec_mz7_j0: m3actuator_ec
  mb7:
    m3actuator_ec_mb7_j0: m3actuator_ec
    m3actuator_ec_mb7_j1: m3actuator_ec
    m3actuator_ec_mb7_j2: m3actuator_ec
    m3actuator_ec_mb7_j3: m3actuator_ec
    m3actuator_ec_mb7_j4: m3actuator_ec
    m3actuator_ec_mb7_j5: m3actuator_ec
    m3actuator_ec_mb7_j6: m3actuator_ec
    m3actuator_ec_mb7_j7: m3actuator_ec
  ms8:
    m3actuator_ec_ms8_j0: m3actuator_ec
    m3actuator_ec_ms8_j1: m3actuator_ec
  mt6:
    m3actuator_ec_mt6_j0: m3actuator_ec
    m3actuator_ec_mt6_j1: m3actuator_ec
  ma29:
    m3actuator_ec_ma29_j0: m3actuator_ec
    m3actuator_ec_ma29_j1: m3actuator_ec
    m3actuator_ec_ma29_j2: m3actuator_ec
    m3actuator_ec_ma29_j3: m3actuator_ec
    m3actuator_ec_ma29_j4: m3actuator_ec
    m3actuator_ec_ma29_j5: m3actuator_ec
    m3actuator_ec_ma29_j6: m3actuator_ec
    m3loadx6_ec_ma29_l0: m3loadx6_ec
  ma30:
    m3actuator_ec_ma30_j0: m3actuator_ec
    m3actuator_ec_ma30_j1: m3actuator_ec
    m3actuator_ec_ma30_j2: m3actuator_ec
    m3actuator_ec_ma30_j3: m3actuator_ec
    m3actuator_ec_ma30_j4: m3actuator_ec
    m3actuator_ec_ma30_j5: m3actuator_ec
    m3actuator_ec_ma30_j6: m3actuator_ec
    m3loadx6_ec_ma30_l0: m3loadx6_ec
  pwr:
    m3pwr_ec_pwr042: m3pwr_ec
    m3pwr_ec_pwr038: m3pwr_ec


