########### M3 CONFIG ######################
#hostname: meka-man
factory_rt_libs:
  - /usr/local/lib/libm3toolbox.so
  - /usr/local/lib/libm3hardware.so
  - /usr/local/lib/libm3chains.so
  - /usr/local/lib/libm3robots.so
  - /usr/local/lib/libm3robot_ctrl.so
  - /usr/local/lib/libm3vehicles.so
factory_py_libs:
  - /usr/local/lib/python2.7/dist-packages/m3/m3meka_factory_proxy.py


sys_test: simc

rt_components:
  pwr:
#     m3pwr_pwr042: m3pwr
    m3pwr_pwr041: m3pwr
#  sys:
#    m3monitor_m0: m3monitor
#   mz4:
#     m3actuator_mz4_j0: m3actuator
#     m3joint_mz4_j0: m3joint_zlift
#     m3joint_shm_mz4_j0: m3joint_zlift_shm
#   mb7:
#     m3omnibase_shm_mb7: m3omnibase_shm
#     m3omnibase_mb7: m3omnibase
#     m3joint_array_mb7: m3joint_array
#     m3actuator_mb7_j0: m3actuator
#     m3joint_mb7_j0: m3joint
#     m3actuator_mb7_j1: m3actuator
#     m3joint_mb7_j1: m3joint
#     m3actuator_mb7_j2: m3actuator
#     m3joint_mb7_j2: m3joint
#     m3actuator_mb7_j3: m3actuator
#     m3joint_mb7_j3: m3joint
#     m3actuator_mb7_j4: m3actuator
#     m3joint_mb7_j4: m3joint
#     m3actuator_mb7_j5: m3actuator
#     m3joint_mb7_j5: m3joint
#     m3actuator_mb7_j6: m3actuator
#     m3joint_mb7_j6: m3joint
#     m3actuator_mb7_j7: m3actuator
#     m3joint_mb7_j7: m3joint
  mh24:
    m3actuator_mh24_j0: m3actuator
    m3actuator_mh24_j1: m3actuator
    m3actuator_mh24_j2: m3actuator
    m3actuator_mh24_j3: m3actuator
    m3actuator_mh24_j4: m3actuator
    m3joint_mh24_j0: m3joint
    m3joint_mh24_j1: m3joint
    m3joint_mh24_j2: m3joint
    m3joint_mh24_j3: m3joint
    m3joint_mh24_j4: m3joint
    m3hand_mh24: m3hand
  mh26:
    m3actuator_mh26_j0: m3actuator
    m3actuator_mh26_j1: m3actuator
    m3actuator_mh26_j2: m3actuator
    m3actuator_mh26_j3: m3actuator
    m3actuator_mh26_j4: m3actuator
    m3joint_mh26_j0: m3joint
    m3joint_mh26_j1: m3joint
    m3joint_mh26_j2: m3joint
    m3joint_mh26_j3: m3joint
    m3joint_mh26_j4: m3joint
    m3hand_mh26: m3hand
  ma29:
    m3actuator_ma29_j0: m3actuator
    m3actuator_ma29_j1: m3actuator
    m3actuator_ma29_j2: m3actuator
    m3actuator_ma29_j3: m3actuator
    m3actuator_ma29_j4: m3actuator
    m3actuator_ma29_j5: m3actuator
    m3actuator_ma29_j6: m3actuator
    m3ctrl_simple_ma29_j0: m3ctrl_simple
    m3ctrl_simple_ma29_j1: m3ctrl_simple
    m3ctrl_simple_ma29_j2: m3ctrl_simple
    m3ctrl_simple_ma29_j3: m3ctrl_simple
    m3ctrl_simple_ma29_j4: m3ctrl_simple
    m3ctrl_simple_ma29_j5: m3ctrl_simple
    m3ctrl_simple_ma29_j6: m3ctrl_simple
    m3joint_ma29_j0: m3joint
    m3joint_ma29_j1: m3joint
    m3joint_ma29_j2: m3joint
    m3joint_ma29_j3: m3joint
    m3joint_ma29_j4: m3joint
    m3joint_ma29_j5: m3joint
    m3joint_ma29_j6: m3joint
    m3arm_ma29: m3arm
    m3dynamatics_right_h2R5_fts_ma29: m3dynamatics
#     m3dynamatics_right_fts_ma29: m3dynamatics
    m3loadx6_ma29_l0: m3loadx6
  ma30:
    m3actuator_ma30_j0: m3actuator
    m3actuator_ma30_j1: m3actuator
    m3actuator_ma30_j2: m3actuator
    m3actuator_ma30_j3: m3actuator
    m3actuator_ma30_j4: m3actuator
    m3actuator_ma30_j5: m3actuator
    m3actuator_ma30_j6: m3actuator
    m3ctrl_simple_ma30_j0: m3ctrl_simple
    m3ctrl_simple_ma30_j1: m3ctrl_simple
    m3ctrl_simple_ma30_j2: m3ctrl_simple
    m3ctrl_simple_ma30_j3: m3ctrl_simple
    m3ctrl_simple_ma30_j4: m3ctrl_simple
    m3ctrl_simple_ma30_j5: m3ctrl_simple
    m3ctrl_simple_ma30_j6: m3ctrl_simple
    m3joint_ma30_j0: m3joint
    m3joint_ma30_j1: m3joint
    m3joint_ma30_j2: m3joint
    m3joint_ma30_j3: m3joint
    m3joint_ma30_j4: m3joint
    m3joint_ma30_j5: m3joint
    m3joint_ma30_j6: m3joint
    m3arm_ma30: m3arm
    m3dynamatics_left_h2R5_fts_ma30: m3dynamatics
#     m3dynamatics_left_fts_ma30: m3dynamatics
    m3loadx6_ma30_l0: m3loadx6
#   mr18:
#     m3humanoid_head_mr14: m3humanoid
#     m3humanoid_right_arm_mr18: m3humanoid
#     m3humanoid_right_left_arm_mr18: m3humanoid
#     m3humanoid_right_left_arm_head_mr18: m3humanoid
#    m3haptic_demo_hd0: m3haptic_demo
#     m3humanoid_left_arm_mr18: m3humanoid
#     m3humanoid_right_arm_head_mr18: m3humanoid
#     m3humanoid_shm18: m3humanoid_shm
#   ms5:
#     m3actuator_ms5_j0: m3actuator
#     m3actuator_ms5_j1: m3actuator
#     m3actuator_ms5_j2: m3actuator
#     m3actuator_ms5_j3: m3actuator
#     m3actuator_ms5_j4: m3actuator
#     m3actuator_ms5_j5: m3actuator
#     m3actuator_ms5_j6: m3actuator
#     m3actuator_ms5_j7: m3actuator
#     m3actuator_ms5_j8: m3actuator
#     m3actuator_ms5_j9: m3actuator
#     m3actuator_ms5_j10: m3actuator
#     m3actuator_ms5_j11: m3actuator
#     m3ctrl_simple_ms5_j0: m3ctrl_simple
#     m3ctrl_simple_ms5_j1: m3ctrl_simple
#     m3ctrl_simple_ms5_j2: m3ctrl_simple
#     m3ctrl_simple_ms5_j3: m3ctrl_simple
#     m3ctrl_simple_ms5_j4: m3ctrl_simple
#     m3ctrl_simple_ms5_j5: m3ctrl_simple
#     m3ctrl_simple_ms5_j6: m3ctrl_simple
#     m3ctrl_simple_ms5_j7: m3ctrl_simple
#     m3ctrl_simple_ms5_j8: m3ctrl_simple
#     m3ctrl_simple_ms5_j9: m3ctrl_simple
#     m3ctrl_simple_ms5_j10: m3ctrl_simple
#     m3ctrl_simple_ms5_j11: m3ctrl_simple
#     m3joint_ms5_j0: m3joint
#     m3joint_ms5_j1: m3joint
#     m3joint_ms5_j2: m3joint
#     m3joint_ms5_j3: m3joint
#     m3joint_ms5_j4: m3joint
#     m3joint_ms5_j5: m3joint
#     m3joint_ms5_j6: m3joint
#     m3joint_ms5_j7: m3joint
#     m3joint_ms5_j8: m3joint
#     m3joint_ms5_j9: m3joint
#     m3joint_ms5_j10: m3joint
#     m3joint_ms5_j11: m3joint
#     m3head_ms5: m3head
#     m3dynamatics_s2r1_simc_ms5: m3dynamatics
#     m3head_s2csp_ctrl_ms5: m3head_s2csp_ctrl    
#     m3ledx2xn_ec_shm_ms5: m3ledx2xn_ec_shm
ec_components:
  mh26:
    m3actuator_ec_mh26_j0: m3actuator_ec
    m3actuator_ec_mh26_j1: m3actuator_ec
    m3actuator_ec_mh26_j2: m3actuator_ec
    m3actuator_ec_mh26_j3: m3actuator_ec
    m3actuator_ec_mh26_j4: m3actuator_ec
  mh24:
    m3actuator_ec_mh24_j0: m3actuator_ec
    m3actuator_ec_mh24_j1: m3actuator_ec
    m3actuator_ec_mh24_j2: m3actuator_ec
    m3actuator_ec_mh24_j3: m3actuator_ec
    m3actuator_ec_mh24_j4: m3actuator_ec
#   ms5:
#     m3actuator_ec_ms5_j0: m3actuator_ec
#     m3actuator_ec_ms5_j1: m3actuator_ec
#     m3actuator_ec_ms5_j2: m3actuator_ec
#     m3actuator_ec_ms5_j3: m3actuator_ec
#     m3actuator_ec_ms5_j4: m3actuator_ec
#     m3actuator_ec_ms5_j5: m3actuator_ec
#     m3actuator_ec_ms5_j6: m3actuator_ec
#     m3actuator_ec_ms5_j7: m3actuator_ec
#     m3actuator_ec_ms5_j8: m3actuator_ec
#     m3actuator_ec_ms5_j9: m3actuator_ec
#     m3actuator_ec_ms5_j10: m3actuator_ec
#     m3actuator_ec_ms5_j11: m3actuator_ec
#     m3ledx2xn_ec_ms5: m3ledx2xn_ec
#   mz4:
#     m3actuator_ec_mz4_j0: m3actuator_ec
#   mb7:
#     m3actuator_ec_mb7_j0: m3actuator_ec
#     m3actuator_ec_mb7_j1: m3actuator_ec
#     m3actuator_ec_mb7_j2: m3actuator_ec
#     m3actuator_ec_mb7_j3: m3actuator_ec
#     m3actuator_ec_mb7_j4: m3actuator_ec
#     m3actuator_ec_mb7_j5: m3actuator_ec
#     m3actuator_ec_mb7_j6: m3actuator_ec
#     m3actuator_ec_mb7_j7: m3actuator_ec
  ma29:
    m3actuator_ec_ma29_j0: m3actuator_ec
    m3actuator_ec_ma29_j1: m3actuator_ec
    m3actuator_ec_ma29_j2: m3actuator_ec
    m3actuator_ec_ma29_j3: m3actuator_ec
    m3actuator_ec_ma29_j4: m3actuator_ec
    m3actuator_ec_ma29_j5: m3actuator_ec
    m3actuator_ec_ma29_j6: m3actuator_ec
    m3loadx6_ec_ma29_l0: m3loadx6_ec
#   ma30:
#     m3actuator_ec_ma30_j0: m3actuator_ec
#     m3actuator_ec_ma30_j1: m3actuator_ec
#     m3actuator_ec_ma30_j2: m3actuator_ec
#     m3actuator_ec_ma30_j3: m3actuator_ec
#     m3actuator_ec_ma30_j4: m3actuator_ec
#     m3actuator_ec_ma30_j5: m3actuator_ec
#     m3actuator_ec_ma30_j6: m3actuator_ec
#     m3loadx6_ec_ma30_l0: m3loadx6_ec
  pwr:
#     m3pwr_ec_pwr042: m3pwr_ec
    m3pwr_ec_pwr041: m3pwr_ec


