########### M3 CONFIG ######################
hostname: meka-man
factory_rt_libs:
  - /usr/local/lib/libm3toolbox.so
  - /usr/local/lib/libm3hardware.so
  - /usr/local/lib/libm3chains.so
  - /usr/local/lib/libm3robots.so
  - /usr/local/lib/libm3robot_ctrl.so
  - /usr/local/lib/libm3vehicles.so

factory_py_libs:
  - /usr/local/lib/python2.7/dist-packages/m3/m3meka_factory_proxy.py

sys_test: simc

left_hand: m3hand_mh26
right_hand: m3hand_mh24

ndof_chains:
  right_arm: 7
  left_arm: 7
  torso: 2
  head: 2
  right_hand: 5
  left_hand: 5
  
rt_components:
#  - controllers:
#    - m3example_test: m3example
- pwr:
   - m3pwr_pwr042: m3pwr #order important?!?!?!
   - m3pwr_pwr038: m3pwr
# - sys:
#  - m3monitor_m0: m3monitor
- mz7: # zlift
   - m3actuator_mz7_j0: m3actuator
   - m3joint_mz7_j0: m3joint_zlift
   - m3joint_shm_mz7_j0: m3joint_zlift_shm
- ma29: # right_arm
   - m3actuator_ma29_j0: m3actuator
   - m3actuator_ma29_j1: m3actuator
   - m3actuator_ma29_j2: m3actuator
   - m3actuator_ma29_j3: m3actuator
   - m3actuator_ma29_j4: m3actuator
   - m3actuator_ma29_j5: m3actuator
   - m3actuator_ma29_j6: m3actuator
   - m3ctrl_simple_ma29_j0: m3ctrl_simple
   - m3ctrl_simple_ma29_j1: m3ctrl_simple
   - m3ctrl_simple_ma29_j2: m3ctrl_simple
   - m3ctrl_simple_ma29_j3: m3ctrl_simple
   - m3ctrl_simple_ma29_j4: m3ctrl_simple
   - m3ctrl_simple_ma29_j5: m3ctrl_simple
   - m3ctrl_simple_ma29_j6: m3ctrl_simple
   - m3joint_ma29_j0: m3joint
   - m3joint_ma29_j1: m3joint
   - m3joint_ma29_j2: m3joint
   - m3joint_ma29_j3: m3joint
   - m3joint_ma29_j4: m3joint
   - m3joint_ma29_j5: m3joint
   - m3joint_ma29_j6: m3joint
   - m3arm_ma29: m3arm
   - m3dynamatics_right_h2R5_fts_ma29: m3dynamatics
   - m3loadx6_ma29_l0: m3loadx6
- ma30: # left_arm
   - m3actuator_ma30_j0: m3actuator
   - m3actuator_ma30_j1: m3actuator
   - m3actuator_ma30_j2: m3actuator
   - m3actuator_ma30_j3: m3actuator
   - m3actuator_ma30_j4: m3actuator
   - m3actuator_ma30_j5: m3actuator
   - m3actuator_ma30_j6: m3actuator
   - m3ctrl_simple_ma30_j0: m3ctrl_simple
   - m3ctrl_simple_ma30_j1: m3ctrl_simple
   - m3ctrl_simple_ma30_j2: m3ctrl_simple
   - m3ctrl_simple_ma30_j3: m3ctrl_simple
   - m3ctrl_simple_ma30_j4: m3ctrl_simple
   - m3ctrl_simple_ma30_j5: m3ctrl_simple
   - m3ctrl_simple_ma30_j6: m3ctrl_simple
   - m3joint_ma30_j0: m3joint
   - m3joint_ma30_j1: m3joint
   - m3joint_ma30_j2: m3joint
   - m3joint_ma30_j3: m3joint
   - m3joint_ma30_j4: m3joint
   - m3joint_ma30_j5: m3joint
   - m3joint_ma30_j6: m3joint
   - m3arm_ma30: m3arm
   - m3dynamatics_left_h2R5_fts_ma30: m3dynamatics
   - m3loadx6_ma30_l0: m3loadx6 
- mh24: # right_hand
   - m3actuator_mh24_j0: m3actuator
   - m3actuator_mh24_j1: m3actuator
   - m3actuator_mh24_j2: m3actuator
   - m3actuator_mh24_j3: m3actuator
   - m3actuator_mh24_j4: m3actuator
   - m3joint_mh24_j0: m3joint
   - m3joint_mh24_j1: m3joint
   - m3joint_mh24_j2: m3joint
   - m3joint_mh24_j3: m3joint
   - m3joint_mh24_j4: m3joint
   - m3hand_mh24: m3hand    
- mh26: # left_hand
   - m3actuator_mh26_j0: m3actuator
   - m3actuator_mh26_j1: m3actuator
   - m3actuator_mh26_j2: m3actuator
   - m3actuator_mh26_j3: m3actuator
   - m3actuator_mh26_j4: m3actuator
   - m3joint_mh26_j0: m3joint
   - m3joint_mh26_j1: m3joint
   - m3joint_mh26_j2: m3joint
   - m3joint_mh26_j3: m3joint
   - m3joint_mh26_j4: m3joint
   - m3hand_mh26: m3hand  
- mb7: # base
    - m3actuator_mb7_j0: m3actuator
    - m3actuator_mb7_j1: m3actuator
    - m3actuator_mb7_j2: m3actuator
    - m3actuator_mb7_j3: m3actuator
    - m3actuator_mb7_j4: m3actuator
    - m3actuator_mb7_j5: m3actuator
    - m3actuator_mb7_j6: m3actuator
    - m3actuator_mb7_j7: m3actuator
    - m3joint_mb7_j0: m3joint
    - m3joint_mb7_j1: m3joint
    - m3joint_mb7_j2: m3joint
    - m3joint_mb7_j3: m3joint
    - m3joint_mb7_j4: m3joint
    - m3joint_mb7_j5: m3joint
    - m3joint_mb7_j6: m3joint
    - m3joint_mb7_j7: m3joint
    - m3joint_array_mb7: m3joint_array
    - m3omnibase_mb7: m3omnibase
    - m3omnibase_shm_mb7: m3omnibase_shm
- ms8: # head
  - m3actuator_ms8_j0: m3actuator
  - m3actuator_ms8_j1: m3actuator
  - m3ctrl_simple_ms8_j0: m3ctrl_simple
  - m3ctrl_simple_ms8_j1: m3ctrl_simple
  - m3joint_ms8_j0: m3joint
  - m3joint_ms8_j1: m3joint
  - m3dynamatics_s3r1_simc_ms8: m3dynamatics
  - m3head_ms8: m3head
  - m3head_s2csp_ctrl_ms8: m3head_s2csp_ctrl # what's that
#- ledm:
#   - m3led_matrix_ec_shm_ms8_l0: m3led_matrix_ec_shm
- mr18:
  - m3humanoid_right_left_arm_head_mr18: m3humanoid  
  - m3humanoid_shm18: m3humanoid_shm
ec_components:
- ma30:
   - m3actuator_ec_ma30_j0: m3actuator_ec
   - m3actuator_ec_ma30_j1: m3actuator_ec
   - m3actuator_ec_ma30_j2: m3actuator_ec
   - m3actuator_ec_ma30_j3: m3actuator_ec
   - m3actuator_ec_ma30_j4: m3actuator_ec
   - m3actuator_ec_ma30_j5: m3actuator_ec
   - m3actuator_ec_ma30_j6: m3actuator_ec
   - m3loadx6_ec_ma30_l0: m3loadx6_ec
- ma29:
   - m3actuator_ec_ma29_j0: m3actuator_ec
   - m3actuator_ec_ma29_j1: m3actuator_ec
   - m3actuator_ec_ma29_j2: m3actuator_ec
   - m3actuator_ec_ma29_j3: m3actuator_ec
   - m3actuator_ec_ma29_j4: m3actuator_ec
   - m3actuator_ec_ma29_j5: m3actuator_ec
   - m3actuator_ec_ma29_j6: m3actuator_ec
   - m3loadx6_ec_ma29_l0: m3loadx6_ec
- mh26:
   - m3actuator_ec_mh26_j0: m3actuator_ec
   - m3actuator_ec_mh26_j1: m3actuator_ec
   - m3actuator_ec_mh26_j2: m3actuator_ec
   - m3actuator_ec_mh26_j3: m3actuator_ec
   - m3actuator_ec_mh26_j4: m3actuator_ec
- mh24:
   - m3actuator_ec_mh24_j0: m3actuator_ec
   - m3actuator_ec_mh24_j1: m3actuator_ec
   - m3actuator_ec_mh24_j2: m3actuator_ec
   - m3actuator_ec_mh24_j3: m3actuator_ec
   - m3actuator_ec_mh24_j4: m3actuator_ec
#- ledm:
#   - m3led_matrix_ec_ms8_l0: m3led_matrix_ec
- ms8:
   - m3actuator_ec_ms8_j0: m3actuator_ec
   - m3actuator_ec_ms8_j1: m3actuator_ec
- mz7:
   - m3actuator_ec_mz7_j0: m3actuator_ec
- mb7:
   - m3actuator_ec_mb7_j0: m3actuator_ec
   - m3actuator_ec_mb7_j1: m3actuator_ec
   - m3actuator_ec_mb7_j2: m3actuator_ec
   - m3actuator_ec_mb7_j3: m3actuator_ec
   - m3actuator_ec_mb7_j4: m3actuator_ec
   - m3actuator_ec_mb7_j5: m3actuator_ec
   - m3actuator_ec_mb7_j6: m3actuator_ec
   - m3actuator_ec_mb7_j7: m3actuator_ec
- pwr:
   - m3pwr_ec_pwr042: m3pwr_ec
   - m3pwr_ec_pwr038: m3pwr_ec


